# Generated by Django 4.1.7 on 2023-05-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('v', 'veg'), ('n', 'non-veg')], default='n', max_length=10, null=True)),
                ('emailAdd', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(default='', max_length=10)),
                ('pricePerGuest', models.IntegerField(default=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=200)),
                ('Pin', models.IntegerField(default=0)),
                ('City', models.CharField(default='', max_length=20)),
                ('State', models.CharField(default='', max_length=20)),
                ('PhoneNo', models.CharField(default='', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
