# Generated by Django 4.1.7 on 2023-05-16 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_alter_restaurant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='')),
                ('resturant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resturant.restaurant')),
            ],
        ),
    ]
