# Generated by Django 4.1.7 on 2023-05-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0004_image_img2_image_img3_image_img4_alter_image_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='img3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='img4',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
