# Generated by Django 4.1.7 on 2023-05-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0005_alter_image_img2_alter_image_img3_alter_image_img4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='City',
            new_name='city',
        ),
    ]
