# Generated by Django 4.1.7 on 2023-05-17 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0007_rename_phoneno_profile_phoneno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Capacity', models.IntegerField(default=10)),
                ('available_time_slots', models.JSONField(default=dict)),
                ('resturant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resturant.restaurant')),
            ],
        ),
    ]
