# Generated by Django 4.1.7 on 2023-05-20 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0009_rename_capacity_table_capacitypertable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
