# Generated by Django 4.1.7 on 2023-05-20 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0010_restaurant_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
    ]
