# Generated by Django 4.1.7 on 2023-05-20 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resturant', '0011_restaurant_closing_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='CapacityPerTable',
            new_name='capacity_per_table',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='pricePerGuest',
            new_name='price_per_guest',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='resturant',
            new_name='restaurant',
        ),
        migrations.AddField(
            model_name='table',
            name='available_time_slots',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('num_guests', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
