# Generated by Django 4.1.7 on 2023-05-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0012_rename_capacitypertable_table_capacity_per_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='resturant',
            new_name='restaurant',
        ),
    ]
