# Generated by Django 4.1.7 on 2023-05-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0013_rename_resturant_image_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='resturant',
            new_name='restaurant',
        ),
    ]
