# Generated by Django 4.1.7 on 2023-05-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0014_rename_resturant_menu_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resturant.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resturant.restaurant'),
        ),
    ]
