# Generated by Django 4.1.7 on 2023-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0016_remove_table_available_time_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='no_of_guests',
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity_per_table',
            field=models.IntegerField(default=5),
        ),
    ]
