# Generated by Django 4.1.7 on 2023-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0018_rename_price_per_guest_table_price_per_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='img1',
            new_name='menu1',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='menu/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='menu/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='menu/'),
        ),
    ]
