# Generated by Django 4.1.7 on 2023-05-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0019_rename_img1_menu_menu1_menu_menu2_menu_menu3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pin',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
