# Generated by Django 4.1.7 on 2023-05-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0020_restaurant_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='emailAdd',
            new_name='email',
        ),
    ]
