# Generated by Django 4.1.7 on 2023-05-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0021_rename_emailadd_restaurant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number_of_table',
            field=models.IntegerField(default=10),
        ),
    ]
